# Generated by Django 3.1 on 2020-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_unlike',
            field=models.IntegerField(null=True),
        ),
    ]
