# Generated by Django 3.1 on 2020-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200831_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date_post',
            field=models.DateTimeField(null=True),
        ),
    ]
