# Generated by Django 3.1 on 2020-08-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200831_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_unlike',
        ),
    ]
